/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */


package uidocument.commons.api.document {

/**
 * Class providing access to
 */
public class Position {

    private var x:Number;
    private var y:Number;
    private var width:Number;
    private var height:Number;

    public function Position(property:Property) {
        this.setX(property.getValue(1));
        this.setY(property.getValue(2));
        this.setWidth(property.getValue(3));
        this.setHeight(property.getValue(4));
    }

    public function setX(x:Number):void {
        this.x = x;
    }

    public function setY(y:Number):void {
        this.y = y;
    }

    public function setWidth(width:Number):void {
        this.width = width;
    }

    public function setHeight(height:Number):void {
        this.height = height;
    }

    public function getX():Number {
        if (this.x == -1) return 0;
        return this.x;
    }

    public function getY():Number {
        if (this.y == -1) return 0;
        return this.y;
    }

    public function getWidth():Number {
        if (this.width == -1) return 200;
        return this.x;
    }

    public function getHeight():Number {
        if (this.height == -1) return 70;
        return this.y;
    }

    public function toString():String {
        return getX() + "," + getY() + "," + getWidth() + "," + getHeight();
    }

}
}
