/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */

//@todo make compatible with actionscript

package uidocument.commons.api.document {
/**
 * Specifies how to update the model. Complete update discards all data in current model and partial udpate
 * onvly overwrites properties that are contained in the update.
 */
public final class UpdateType {
    /*
     pub static final var COMPLETE:UpdateType;

     pub static final var PARTIAL:UpdateType;

     pub static final var INVALIDATE:UpdateType;

     pub static final var UNAVAILABLE:UpdateType;

     pub static final var COMPONENT:UpdateType;

     pub static final var RECOVERY:UpdateType;

     pub static final var PERSISTENT:UpdateType;
     */
}
}
